### ISSUE TITLE
Updating state between browsers

### ISSUE THREAD

**Issue by jonoforbes** [brechtbilliet/winecellar#13]
Hi Brecht,

Suppose I have two browsers open with the same user logged in.

In browser A I have an EditStockPage open on a particular Wine. In browser B I am looking at the StockPage. I remove the Wine from browser B. 

This sends a redux action to the browser A to remove the wine and the DetailWineFormComponent doesn't update. That seems fine as in browser A I want to retain the form data. 

Then in the browser A I try to update the wine. The server crashes because 

`/Users/jonoforbes/Developer/Ether/WineCellarBackend/out/controller/WineController.js:67
                this.handleRt(userId, req, { type: DATA_WINES_UPDATE, payload: { _id: response._id, contact: req.body } });
TypeError: Cannot read property '_id' of null
    at Query.WineSchema_1.Wine.findOneAndUpdate (/Users/jonoforbes/Developer/Ether/WineCellarBackend/out/controller/WineController.js:67:98)
`

Fair enough. So I change the server's put method so that the backend will simply post a new Wine if the response is null:

```
@Put("/:id")
    public put(@Req()req: Request, @Res() res: Response): void {
        let userId: string = handleAuth(req, res);
        Wine.findOneAndUpdate({
            _id: new ObjectID(req.params.id),
            userId: new ObjectID(userId)
        }, req.body, (error: any, response: any) => {
            if (response == null) {
                this.post(req, res);
            }
            else {
                this.handleRt(userId, req, {type: DATA_WINES_UPDATE, payload: {_id: response._id, wine: req.body}});
                res.send(response);
            }
        });
    }
```

The server happily does so and keeps the same ObjectID for the new(old) Wine. This is exactly what I want. In browser B the state gets updated but in browser A (where I update the Wine from) the state doesn't change at all. I refresh the page and browser A syncs with browser B. What am I doing wrong?

**Comment by KwintenP** [comment]
Hi,

The process you are describing will make sure there is some inconsistency with ids. Let me explain.

When you remove the wine (with id 1 fe.) in browser B, browser A will be notified that the wine has been deleted and will delete this one from the store. In the store in browser A at that time, you no longer have a wine with id 1.
Since you are on the edit page, you keep the form data of the wine you are editing (and was deleted in browser B) in browser A. This is still the one with id 1 (which is no longer in the store). 
When you save this form in browser A, a request is send to the backend to update. You changed the update method to make it an insert if it doesn't exist (Lets say that this creates a new Wine with id 2).  In that scenario the backend call works and browser B will be notified that it has been updated and changes the store to match the correct state.
Browser A however will also try to update the store by sending an 'DATA_UPDATE_WINES' action to the store. Lets look at the code.

```
updateWine(id: string, wine: Wine): void {
        let action = new UpdateWine(id, wine);
       // here it will dispatch the update action to the store
        this.store.dispatch(action);
        this.stockService.update(id, wine).subscribe(() => {
        }, () => this.handleError(action));
}
```

This is an update action. If we look at the implementation in the reducer on how this action is handled:

```
case wine.ActionTypes.WINES_UPDATE:
            return state.map(item => item._id === action.payload._id ? Object.assign({}, action.payload.wine) : item);

```
We are replacing the one in our store with id 1. We do however no longer hold one with id 1 in the store, so there is not one to replace. This means the store does not get updated and you don't see the value on the screen.

If you reload the page, the store state gets refreshed and the values are visible.

You could fix this by changing the implementation in the reducer for the update to add the wine to the array if it didn't hold one with the same id. This would align with what you did in the backend.

**Comment by jonoforbes** [comment]
Kwinten thanks so much. Something like this?

```
case wine.ActionTypes.WINES_UPDATE:
            if (state.filter(item => item._id === action.payload._id).length > 0) {
                console.log("wine already in array");
                return state.map(item => item._id === action.payload._id ? Object.assign({}, action.payload.wine) : item);
            }
            else {
                console.log("wine replaced in array");
                // return state;
                return [...state, action.payload.wine];
            };
```
I'm not sure exactly what you mean by
> You changed the update method to make it an insert if it doesn't exist (Lets say that this creates a new Wine with id 2).

Shouldn't the new Wine retain id 1 as the object being inserted already has an id property?

EDIT: using _.includes only works if the Wine object was not changed at all
