### ISSUE TITLE
fetchWine API call

### ISSUE THREAD

**Issue by jonoforbes** [brechtbilliet/winecellar#14]
Hey guys,

I'm trying to understand why (if for any reason other than out of habit) the StockSandbox uses a call to the backend to retrieve a specific wine rather than simply filtering the wines$ observable?

Is there any reason not to do this?

i.e.

```
fetchWine(id: string): Observable<Wine> {
        return this.wines$.switchMap((wines: Wine[]) => {
            return wines.filter((wine: Wine) => {
                return wine._id == id;
            });
        });
    }
```

**Comment by KwintenP** [comment]
Good question. Originally this was done because the application wasn't realtime. 

When you load the app, you fetch the wines in the 'list' overview en you put them into the store. This list can be there for quite some time (say a user opens the app and loads the wines and then waits 10 minutes to go to the edit page). If you would fetch the wine to change from the store, you might be editing stale data. 
That's why here it fetches the wine you want to edit instead of taking data from the store, since this might be already out of date. 

If you keep your store up to date with realtime data (like we added later on), this isn't really necessary any more and you could fetch the data from the store instead of the backend. But that's kind of a functional question.

Btw, your code snippet should use `map` instead of `switchMap` ;).

I hope that answers your question.
